/// Flutter icons GroupHourGlass
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'GroupHourGlass';

  static const IconData group_hour_glass = IconData(0xe800, fontFamily: _kFontFam);
}
